### ISSUE TITLE
DataGrip omnisci-jdbc driver NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by armandleopold** [omnisci/omnisci-jdbc#26]
On JetBrains DataGrip 2019.3
When i import the omnisci-jdbc driver and try to connect to it.
it state : 
```Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
  at com.omnisci.jdbc.OmniSciDriver.&lt;clinit&gt;(OmniSciDriver.java:37)
  at java.base/java.lang.Class.forName0(Native Method)
  at java.base/java.lang.Class.forName(Class.java:315)
  at com.intellij.database.remote.RemoteJdbcServer.main(RemoteJdbcServer.java:14)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
  ... 4 more.
.
```
When we look at the .jar there is in fact no dependencies. How can i make it work ?

**Comment by armandleopold** [comment]
I had to add : 
```
<plugin>
  <artifactId>maven-assembly-plugin</artifactId>
  <executions>
    <execution>
      <phase>package</phase>
      <goals>
        <goal>single</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <descriptorRefs>
      <descriptorRef>jar-with-dependencies</descriptorRef>
    </descriptorRefs>
  </configuration>
</plugin>
```
Generating a jar with dependencies.
And now it works

**Comment by randyzwitch** [comment]
Thanks for reporting. The JAR published to Maven is slim, which gives people the option of adding the dependencies they might need as part of a bigger project. Of course, this doesn't make the best experience when using an IDE.

For DataGrip, you could also add the JARs manually, or use the JDBC driver provided by the source OmniSci distribution (which is a fat jar with all the dependencies)
